#pragma once
#include "NativeGameplayTags.h"

namespace EmberGameplayTags
{
	// Ability
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_Death);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_HitReact);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_Attack);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_Attack_Normal);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_Attack_Heavy);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_Phase);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AI_Ability_GiantForm);

	// Status
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_HitReact);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Phase);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_GiantForm);
	
	// Gameplay Event
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HitReact);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	EMBER_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
};
